bug fix: typo
d-edison/theoddsapi pull request #1
Opened 2021-07-26 08:57 UTC by JohnGavin

eu option was not included
au option was included twice

2021-07-26 21:35 UTC, JohnGavin commented
added an enhancement/bug fix (commit: cbb80bef48e1b4d9081b6faf6a8ae485499a7d54)
'active' column might be expected to be logical as it only contains TRUE/FALSE (and not of type character).

2021-08-13 21:09 UTC, d-edison commented on R/get-odds.R
> +    region <- match.arg(region, c("us", "eu", "uk", "au"))
Good catch!

2021-08-13 21:14 UTC, d-edison commented on R/get-sports.R
> +        mutate(active = active %>% as.logical())
Yes, this should be logical, as should `has_outrights`. Could you remove that comment and switch this to 

```R
dplyr::mutate(
    dplyr::across(c(active, has_outrights), as.logical)
)
```

2021-08-13 21:15 UTC, d-edison requested changes
Appreciate the PR! Some small suggested changes

2021-08-14 19:38 UTC, merged